### ISSUE TITLE
visR missing from renv.lock

### ISSUE THREAD

**Issue by SulevR** [oxford-pharmacoepi/MegaStudy#11]
visR is not installed via renv, but is required by CDMConnector.

Therefore, renv::restore() results with an error:

ERROR: lazy loading failed for package ‘CDMConnector’
* removing ‘/Users/sulevr/MegaStudy/IncidencePrevalence Code/renv/staging/1/CDMConnector’
install of package 'CDMConnector' failed [error code 1]

Installing the CDMConnector failed in the first attempt:
  there is no package called ‘visR’

**Comment by tiozab** [comment]
THanks @SulevR,  I became aware of this error and had already changed the code, but not before you had started the run it seems ;-) sorry about that.
