### ISSUE TITLE
Use drug utilisation for creating outcome cohort - cohort exit at drug end date

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/MegaStudy#15]
https://github.com/oxford-pharmacoepi/MegaStudy/blob/3bd367ddc188fe4ebdd2837720677b4ba0aaa914/IncidencePrevalence%20Code/RunIncidencePrevalence.R#L46

**Comment by tiozab** [comment]
generateDrugUtilisationCohortSet(
  cdm,
  name,
  conceptSet,
  durationRange = c(1, Inf),
  imputeDuration = "none",
  gapEra = 0,
  priorUseWashout = 0,
  priorObservation = 0,
  cohortDateRange = as.Date(c(NA, NA)),
  limit = "all"
)
from the article...
translates to
cdm <- generateDrugUtilisationCohortSet(
  cdm = cdm,
  name = "drug_cohorts",
  conceptSet = concept_drugs,
  cohortDateRange = as.Date(c('2010-01-01','2024-12-31')),
  limit = "all"
)
