### ISSUE TITLE
Feasibility code: n counts not being properly obscured?

### ISSUE THREAD

**Issue by sampo-tays** [oxford-pharmacoepi/MegaStudy#17]
In some of our feasibility result files, there are very small n counts being reported without being obscured. While for some drugs the numbers are obscured (with NAs and results_obscured=TRUE), there are several rows where n counts in the range of 1-9 are reported.

The problematic tables and fields are:
- missingValuesOverall.csv: n_records_not_missing_value, n_records_missing_value
- missingValuesByConcept.csv: n_records_not_missing_value, n_records_missing_value

**Comment by tiozab** [comment]
@sampo-tays thanks for your comment. 

we did not consider a reporting of the number of missing values a sensitive information. 
We look for the value of the number of records and if that value is below the minimum cell count then obscure any related information, so if a drug has 100 records, and 99 of them have a missing quantity and 1 of them has a missing quantity then this is not sensitive information. 
we refrain from reporting low number of users / records to prevent possible identification, but not when we count the frequency of missingness (unless the overall number of records is below the minimum cell count).
Does that make sense?

**Comment by sampo-tays** [comment]
Yes, thank you, it makes sense. :) We have now uploaded the files.

**Comment by tiozab** [comment]
Thank you, always great to double check! we are not perfect, please let us know if there are other instances where you see unusually low counts!! Always appreciated!
