### ISSUE TITLE
InGef outpaitent diagnoses mapped to OBSERVATION table

### ISSUE THREAD

**Issue by raeleesha-norris** [oxford-pharmacoepi/MegaStudy#19]
Hi all,

The InGef database is still in the process of mapping to OMOP, and we would like to inform you that, due to the structures of how diagnoses are recorded in the inpatient vs outpatient setting, these data have had to be mapped differently.

For inpatient diagnoses, we have applied the "regular" mapping process, where diagnoses are written into the appropriate table according to their domain, i.e. the CONDITION_OCCURRENCE table contains the inpatient diagnoses to which an OMOP concept from the 'Condition' domain can be assigned, ICD codes from the 'Measurement' domain are written to the MEASUREMENT table, etc.

Outpatient diagnoses, on the other hand, have to be stored in the OBSERVATION table, regardless of the ICD domain. This is because outpatient data are stored strictly on a quarterly basis in our database, meaning that we simply do not have exact diagnosis dates for the mandatory date field in the above-mentioned tables regarding outpatient diagnosis data.

Perhaps this is a peculiarity that affects other data sources as well!

Best,
Raeleesha

**Comment by tiozab** [comment]
@raeleesha-norris thanks for letting us know. 
I have confirmed with @edward-burn that we cannot add more tables to our indication search, because it will make the code lists explode with a lot of weird codes and will make more bad than good. However, coming out of this discussion, we will now add the observation and measurement table in the large scale characterisation part.

**Comment by raeleesha-norris** [comment]
@tiozab Thank you for the update!
Regarding outpatient diagnoses in the observation table, we decided to map all types of diagnoses available in our data (including confirmed, suspected, exclusion, and history of), and included this status within the qualifier_concept_id variable. Is this something that can be taken into account in the characterisation code, or something that we can subsequently adjust? We generally only regard confirmed diagnoses (qualifier_concept_id 32893) as valid.

**Comment by tiozab** [comment]
@raeleesha-norris thanks for letting us know. 
Unfortunately we do not work with this field and therefore cannot take it into consideration. 
Let's see how your results look like and interpret them accordingly (knowing how your data has been mapped).
