### ISSUE TITLE
SQL error running executeChecks

### ISSUE THREAD

**Issue by eric-fey-hus** [oxford-pharmacoepi/MegaStudy#2]
Database connection work fine. Details:
```R
db <- dbConnect(odbc::odbc(),
                Driver = "{ODBC DRIVER 18 for SQL Server}", ...
```
Error occurs when running line 36 in `RunFeasibility.R`: `executeChecks( ...)`:

> Error: nanodbc/nanodbc.cpp:1769: 42S02: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'tempdb.pdw.sysobjects'. 
><SQL> 'select * from tempdb..sysobjects'

sessionInfo:

> R version 4.2.1 (2022-06-23 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 22000)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Europe.utf8  LC_CTYPE=English_Europe.utf8    LC_MONETARY=English_Europe.utf8 LC_NUMERIC=C                   
> [5] LC_TIME=English_Europe.utf8    
> 
> attached base packages:
> [1] stats     graphics  grDevices datasets  utils     methods   base     
> 
> other attached packages:
>  [1] DrugExposureDiagnostics_1.0.0 zip_2.3.0                     log4r_0.4.3                   here_1.0.1                   
>  [5] CDMConnector_1.1.2            CirceR_1.3.1                  dbplyr_2.3.4                  dplyr_1.1.3                  
>  [9] DBI_1.1.3                     RPostgres_1.4.5               odbc_1.3.5                   
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.11       pillar_1.9.0      compiler_4.2.1    remotes_2.4.2.1   tools_4.2.1       bit_4.0.5         jsonlite_1.8.7   
>  [8] lifecycle_1.0.3   tibble_3.2.1      checkmate_2.2.0   pkgconfig_2.0.3   rlang_1.1.1       cli_3.6.1         rstudioapi_0.15.0
> [15] curl_5.1.0        rJava_1.0-6       stringr_1.5.0     withr_2.5.1       generics_0.1.3    vctrs_0.6.4       hms_1.1.3        
> [22] bit64_4.0.5       rprojroot_2.0.3   tidyselect_1.2.0  glue_1.6.2        R6_2.5.1          fansi_1.0.5       purrr_1.0.2      
> [29] blob_1.2.4        magrittr_2.0.3    backports_1.4.1   renv_1.0.3        utf8_1.2.3        stringi_1.7.12

**Comment by eric-fey-hus** [comment]
@tiozab Thanks! @pasirikala tagging you here as you might have better insight.

DBMS is synapse, more precisely: dedicated SQL pool in Azure Synapse Analytics.

The connection work fine and we can use the usual OMOP tables:

```R
db <- dbConnect(odbc::odbc(),
                Driver = "{ODBC DRIVER 18 for SQL Server}",
                Server = "MYSERVER",  
                Database = "MYDB",
                UID = "MYUSER", 
                PWD = "MYPWD",
                )
```
Then I tested the connection using `DBI::dbListTables(db) `, which worked fine. 

For your test I did
```R
#Test to resolve issue: https://github.com/oxford-pharmacoepi/MegaStudy/issues/2
cdm <- cdmFromCon(
  con = db,
  cdmSchema = c(schema = "omop54"),
  writeSchema = c(schema = "ohdsieric", prefix = "mega_"),
  cdmName = "HUS"
)
cdm$person
```
 I am not showing the result of cdm$person obviously, that's sensitive info :-), but it worked just fine. 

I think the issue here is how to list the temp tables on Azure Synapse. Could not get that working, and from what I understand temp tables do not persist between queries. Ref: https://learn.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-tables-temporary

**Comment by tiozab** [comment]
@ginberg since you are the maintainer of the DrugUtilisation Package, can you help me? Maybe we can continue with this issue in the DrugExposureDiagnostics Package? https://github.com/darwin-eu/DrugExposureDiagnostics
@edward-burn, what do you think?

**Comment by tiozab** [comment]
@eric-fey-hus  I think same issue as https://github.com/oxford-pharmacoepi/CancerSurvivalWp2Analysis/issues/25
I am sorry but this is out of my hands, so for the time being (because your DBMS is not supported), you will not be able to participate in the megastudy @martapineda

**Comment by eric-fey-hus** [comment]
@tiozab We are working on the SQL Server version. In parallel, we would also like to get this working with our Synapse backend. For DatabaseConenctror using SQLRender we could solve this by adding a few small substitution patterns in replacementPatters.csv of SQLRender, and we had Synapse supported: 

```
synapse,DROP TABLE IF EXISTS #@table;,"IF OBJECT_ID('tempdb..#@table', 'U') IS NOT NULL DROP TABLE #@table;"
synapse,DROP TABLE IF EXISTS @table;,"IF OBJECT_ID('@table', 'U') IS NOT NULL DROP TABLE @table;"
synapse,CREATE TABLE IF NOT EXISTS @table (@definition);,"IF OBJECT_ID('@table', 'U') IS NULL CREATE TABLE @table (@definition);"
````

Hoping to do the same here. It would be great if you could point us towards where the root issues arises (what package, function, etc?), then we can look for a solution there.

**Comment by tiozab** [comment]
@eric-fey-hus the package can be found here
https://github.com/darwin-eu/DrugExposureDiagnostics

You said you got the error when running the executeChecks function (however, this function calls a ton of functions ;-))

but I am not sure if that is what you wanted to know?

**Comment by tiozab** [comment]
@eric-fey-hus congrats on uploading the results!! @martapineda. do you mind sharing with us how you got it to work? @edward-burn
