### ISSUE TITLE
Issue connecting to Teams space

### ISSUE THREAD

**Issue by raeleesha-norris** [oxford-pharmacoepi/MegaStudy#22]
Hi all,

InGef has so far not been able to connect to the project Teams space where we will need to upload our results. When attempting to access the space using the links provided by email, we have only received error messages stating that we do not have access to the sharepoint directory.

Could you please advise on the steps we need to take in order to be able to log into the Teams space?

Best,
Raeleesha

**Comment by tiozab** [comment]
@raeleesha-norris please write your email address to Montse and she will add you. She has already added Dirk
