### ISSUE TITLE
Error while creating Denominator Cohort Set

### ISSUE THREAD

**Issue by IdISBa-PRISIB-Pau** [oxford-pharmacoepi/MegaStudy#24]
While running the RunIncidencePrevalence.R script, an error arises:

`Error in generateDenominatorCohortSet(cdm = cdm, name = "denominator",  : 
  unused argument (overwrite = TRUE)`

Removing the overwrite argument from the 76th line of the script appears to work

**Comment by tiozab** [comment]
@IdISBa-PRISIB-Pau thanks for posting. Did you employ the renv()? it seems like you are not using the correct version of IncidencePrevalence. The overwrite is not an unused argument in the IncidencePrevalence package 0.6.0
