### ISSUE TITLE
Error: nanodbc/nanodbc.cpp:1769: 00000: [Simba][Hardy] (80) Syntax or semantic analysis error thrown in server while executing query.

### ISSUE THREAD

**Issue by Elyne** [oxford-pharmacoepi/MegaStudy#25]
Hi, I am getting following error when running IncidencePrevalence. Our database is on databricks, I am using an ODBC driver to connect to a spark cluster as a database and am running the code locally.

Error: nanodbc/nanodbc.cpp:1769: 00000: [Simba][Hardy] (80) Syntax or semantic analysis error thrown in server while executing query. Error message from server: org.apache.hive.service.cli.HiveSQLException: Error running query: [INVALID_IDENTIFIER] org.apache.spark.sql.catalyst.parser.ParseException: 
[INVALID_IDENTIFIER] The identifier win1-number_records is invalid. Please, consider quoting it with back-quotes  
<SQL> 'CREATE OR REPLACE TEMPORARY VIEW 
`dbplyr_017` AS
SELECT
  `cohort_definition_id`,
  `number_records`,
  `number_subjects`,
  `reason_id`,
  `reason`,
  CASE WHEN ((`excluded_records` IS NULL)) THEN (LAG(`number_records`, 1, NULL) OVER `win1` - `number_records`) WHEN NOT ((`excluded_records` IS NULL)) THEN `excluded_records` END AS `excluded_records`,
  CASE WHEN ((`excluded_subjects` IS NULL)) THEN (LAG(`number_subjects`, 1, NULL) OVER `win1` - `number_subjects`) WHEN NOT ((`excluded_subjects` IS NULL)) THEN `excluded_subjects` END AS `excluded_subjects`
FROM (
  SELE

**Comment by tiozab** [comment]
thank you, this is part of the attrition step, when using the function incidenceAttrition(inc) 
I am wondering where the name "win1-" comes from ? is that your prefix or something ? 
@edward-burn any idea what is happening?

**Comment by Elyne** [comment]
I do not know where 'win1-' comes from, I assume its a variable field name actually as it does not approach any of the settings I have added in CodeToRun.R. I was able to run the Eligibility step fine, but cannot run IncidencePrevalence.

**Comment by tiozab** [comment]
I am very sorry about this @Elyne  let's keep this issue open until there is news from @ablack3

**Comment by tiozab** [comment]
@ablack3 do you think it would be of help if @sebastiaan101 helped you getting spark supported for CDMConnector for @Elyne to join the study?

**Comment by tiozab** [comment]
resolved by using SQL SERVER instead.
