### ISSUE TITLE
There is no renv.lock file for 'IncidencePrevalence Code'

### ISSUE THREAD

**Issue by festerman** [oxford-pharmacoepi/MegaStudy#27]
If you are advocating the use of renv, there has to be a renv.lock file ...

**Comment by tiozab** [comment]
you are absolutely right, sorry about that, I am making an update right now, it took a bit longer than expected

**Comment by tiozab** [comment]
which database management system do you use?

**Comment by tiozab** [comment]
if you do not use sql server you can use this renv.lock file
[renv.lock IncPrev.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/14449730/renv.lock.IncPrev.txt)

**Comment by tiozab** [comment]
I pushed this file now to the folder level, sorry that it was not there earlier, we are trying to update a single package for sql server and it is more difficult than expected.

**Comment by festerman** [comment]
Got the lock-file to work, with minor tweaks (xml2 to 1.3.6, since 1.3.5 does not build/run on the latest libxml2, and dropped two we're not using).
