### ISSUE TITLE
Post-validation of the prevalence estimates

### ISSUE THREAD

**Issue by JWaste** [oxford-pharmacoepi/MegaStudy#31]
We have run the code on our data and are trying to validate if the prevalence are correct.

Some issues:
-We loose many persons from the analysis due to the attrition classified as 'No observation time available during the study period'. This does not  seem to agree with how we would normally calculate the prevalence.
-The denominator does not reflect our dynamic cohort. It seems we are only loosing persons after 2010 and no new persons are added thereafter.

How should we go about these issues?

Best,
Jonas

**Comment by JWaste** [comment]
DB: KI-MEB
DBMS: MSSQL

**Comment by tiozab** [comment]
@JWaste : The "attrition reason" _No observation time available during study period_ says that people are dropped whose observation_period_start_date is after study end or whose observation_period_end_date is before study start. It is ok to lose a few people this way. 
what do you mean by "-The denominator does not reflect our dynamic cohort. It seems we are only loosing persons after 2010 and no new persons are added thereafter" I do not understand this.

**Comment by martapineda** [comment]
Hi Jonas, probably that may not be it but, if you think individuals turning 65 are not being included in the analysis, I am wondering if the problem is how the valid observation period of these specific patients was defined in your database.

**Comment by JWaste** [comment]
Thanks for the suggestion, Marta. Yes, we will start by inspecting those.
