### ISSUE TITLE
Problem in Feasibility Code

### ISSUE THREAD

**Issue by prubiom** [oxford-pharmacoepi/MegaStudy#33]
Hello, everyone

I'm running the code of "Feasibility Code" and I have obtained a few warnings regarding the population. This warnings said "Population after earliestStartDate smaller than sample". I have seen the logs and the snapshot and I have figured out that my earliestStarDate is in 2026, and I'm sure this is not possible. 

I think than for that reason, finally at the end of the code, I haven't obtained the .zip with the results. During the analysis of the "ingredients", some codes have an Inf value or any value. 

Do you have an idea to solve this problem or what is the reason why my earliestDateStart is not right? can be a problem of our omop?

Thank you in advance!

![image](https://github.com/oxford-pharmacoepi/MegaStudy/assets/162588455/741ed8b1-c4ea-4699-8232-737c052b4099)
(i have attached a image with the errors)

**Comment by tiozab** [comment]
@prubiom, it is ok if your CDM does not have ingredient concept 36857573, other datapartners have had the same problem, especially also for ingredient concept 36863408.
Image from EHDEN teams channel:
![image](https://github.com/oxford-pharmacoepi/MegaStudy/assets/94674809/5b76aff9-7b10-4ca0-96fa-e1faf992a036)

Feel free to remove these two ingredient codes from the code "RunFeasibility.R" in line 72 and 83 and try to re-run the code.

**Comment by tiozab** [comment]
@prubiom for the dates, yes you will have to check your data and whether there was a problem in the mapping. there will be some errors (data is messy, so you may get occasional weird dates) but if all your data has weird start dates such as 2026 than definitely going over the books!
