### ISSUE TITLE
DUS code crashes because column "subexposure_end_date" does not exist

### ISSUE THREAD

**Issue by tiozab** [oxford-pharmacoepi/MegaStudy#36]
@bmosseveld to follow-up your issue here that occurred in the adding of  drug use information.

Error: Failed to prepare query: ERROR:  column "subexposure_end_date" does not exist
LINE 25:     WHERE (("subexposure_end_date" IS NULL))
                     ^
HINT:  There is a column named "subexposure_end_date" in table "*SELECT* 1", but it cannot be referenced from this part of the query.
In addition: There were 50 or more warnings (use warnings() to see the first 50)

@catalamarti suggests to use default values of addDrugUse and to put a logger if the code fails at a certain ingredient or already at the beginning. 

@bmosseveld if you could run the below code and let us know how it goes that would be great, it is an adaptation from line 332 where the code started to fail. so everything before needs to be in your connection / environment.

source("applyFilterIngforUse.R")

ingredients <- as.integer(c(19098548,
                 1347450,
                 1594587,
                 912803,
                 40171288,
                 780442,
                 45892599,
                 1741122,
                 45892906,
                 1333379,
                 40239665,
                 1536743,
                 1742432,
                 1348407,
                 1525746,
                 1734104,
                 1750500,
                 1729720,
                 1728416,
                 1713332,
                 1759842,
                 1777806,
                 1774470,
                 1709170,
                 1778162,
                 1746114,
                 19136187,
                 1307515,
                 1186087,
                 42904205,
                 1510627,
                 1361580,
                 1151789,
                 937368,
                 912263,36857573,
                 19041065,
                 1114375,
                 19080982,
                 1397141,
                 718583,
                 40242044,
                 40168938,
                 36878937,
                 35200405,
                 37003361,
                 1311078,902730,36863408,
                 1311799,
                 19078097,
                 903643,
                 19012565,
                 19034726,
                 19010482,
                 950637,
                 1503983,
                 40174604,
                 42800246,
                 36878851
))
names <- c("tenecteplase",
           "alteplase",
           "sarilumab",
           "verteporfin",
           "tocilizumab",
           "varenicline",
           "ceftolozane",
           "tazobactam",
           "C1 esterase inhibitor",
           "arsenic trioxide",
           "belatacept",
           "ganirelix",
           "tigecycline",
           "imiglucerase",
           "agalsidase beta",
           "azithromycin",
           "clarithromycin",
           "penicillin V",
           "penicillin G",
           "amoxicillin",
           "clavulanate",
           "ceftriaxone",
           "cefotaxime",
           "meropenem",
           "cefuroxime",
           "piperacillin",
           "streptokinase",
           "urokinase",
           "abatacept",
           "tofacitinib",
           "baricitinib",
           "upadacitinib",
           "etanercept",
           "infliximab",
           "certolizumab pegol",	"CERTOLIZUMAB",
           "golimumab",
           "anakinra",
           "ranibizumab",
           "bevacizumab",
           "nicotine",
           "icatibant",
           "ecallantide",
           "Conestat alfa",
           "lanadelumab",
           "berotralstat",
           "cytarabine","Cytarabine liposomal","CYTARABINE 5'-PHOSPHATE",
           "daunorubicin",
           "idarubicin",
           "tretinoin",
           "mycophenolic acid",
           "sirolimus",
           "cyclosporine",
           "tacrolimus",
           "cetrorelix",
           "velaglucerase alfa",
           "taliglucerase alfa",
           "Agalsidase alfa"
)

inc_use_summary <- tibble::as_tibble(NULL)
for (j in seq_along(ingredients)) {
  ingredient <- ingredients[j]
  name <- names[j]
  
info(logger, paste0(ingredient))

  use_drug_cohort <- applyFilterIngforUse(cdm[["inc_pat"]], name) %>%
    addDrugUse(
      ingredientConceptId = ingredient ,
      duration = TRUE,
      quantity = TRUE,
      dose = TRUE,
      gapEra = 0,
      eraJoinMode = "zero",
      overlapMode = "sum",
      sameIndexMode = "sum",
      imputeDuration = "none",
      imputeDailyDose = "none"
    ) %>%
    summariseDrugUse(
      strata = list("Calendar Year" = "calendar_year")
      ) %>%  suppress(minCellCount = 5) %>%
    mutate(variable_level = name) %>%
    mutate(cohort_definition_id = as.integer(str_sub(group_level, 8))) %>%
    inner_join(cdm[["inc_pat"]] %>% select(cohort_definition_id, outcome_cohort_name) %>% distinct(), by = c("cohort_definition_id"), copy = TRUE ) %>%
    select(-"cohort_definition_id") %>%
    filter(variable_name %in% c("number subjects","number records","duration","number_exposures","cumulative_quantity",
                                "initial_quantity","initial_daily_dose_milligram","cumulative_dose_milligram"))
  
  inc_use_summary <- bind_rows(inc_use_summary,use_drug_cohort)
}

**Comment by bmosseveld** [comment]
I tried the code but got the same error.
See the attached console output and log file.
[2024-03-27 02 IPCI_log.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/14774710/2024-03-27.02.IPCI_log.txt)
[2024-03-27 02 Console.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/14774711/2024-03-27.02.Console.txt)

**Comment by tiozab** [comment]
@bmosseveld that was actually great, we now know that imiglucerase is where it breaks.
Can you check if you see some weird drug dates in that drug?

Next can you just run this again? I am now excluding the "imiglucerase" drug

source("applyFilterIngforUse.R")

ingredients <- as.integer(c(19098548,
1347450,
1594587,
912803,
40171288,
780442,
45892599,
1741122,
45892906,
1333379,
40239665,
1536743,
1742432,
#1348407,
1525746,
1734104,
1750500,
1729720,
1728416,
1713332,
1759842,
1777806,
1774470,
1709170,
1778162,
1746114,
19136187,
1307515,
1186087,
42904205,
1510627,
1361580,
1151789,
937368,
912263,36857573,
19041065,
1114375,
19080982,
1397141,
718583,
40242044,
40168938,
36878937,
35200405,
37003361,
1311078,902730,36863408,
1311799,
19078097,
903643,
19012565,
19034726,
19010482,
950637,
1503983,
40174604,
42800246,
36878851
))
names <- c("tenecteplase",
"alteplase",
"sarilumab",
"verteporfin",
"tocilizumab",
"varenicline",
"ceftolozane",
"tazobactam",
"C1 esterase inhibitor",
"arsenic trioxide",
"belatacept",
"ganirelix",
"tigecycline",
#"imiglucerase",
"agalsidase beta",
"azithromycin",
"clarithromycin",
"penicillin V",
"penicillin G",
"amoxicillin",
"clavulanate",
"ceftriaxone",
"cefotaxime",
"meropenem",
"cefuroxime",
"piperacillin",
"streptokinase",
"urokinase",
"abatacept",
"tofacitinib",
"baricitinib",
"upadacitinib",
"etanercept",
"infliximab",
"certolizumab pegol", "CERTOLIZUMAB",
"golimumab",
"anakinra",
"ranibizumab",
"bevacizumab",
"nicotine",
"icatibant",
"ecallantide",
"Conestat alfa",
"lanadelumab",
"berotralstat",
"cytarabine","Cytarabine liposomal","CYTARABINE 5'-PHOSPHATE",
"daunorubicin",
"idarubicin",
"tretinoin",
"mycophenolic acid",
"sirolimus",
"cyclosporine",
"tacrolimus",
"cetrorelix",
"velaglucerase alfa",
"taliglucerase alfa",
"Agalsidase alfa"
)

inc_use_summary <- tibble::as_tibble(NULL)
for (j in seq_along(ingredients)) {
ingredient <- ingredients[j]
name <- names[j]

info(logger, paste0(ingredient))

use_drug_cohort <- applyFilterIngforUse(cdm[["inc_pat"]], name) %>%
addDrugUse(
ingredientConceptId = ingredient ,
duration = TRUE,
quantity = TRUE,
dose = TRUE,
gapEra = 0,
eraJoinMode = "zero",
overlapMode = "sum",
sameIndexMode = "sum",
imputeDuration = "none",
imputeDailyDose = "none"
) %>%
summariseDrugUse(
strata = list("Calendar Year" = "calendar_year")
) %>% suppress(minCellCount = 5) %>%
mutate(variable_level = name) %>%
mutate(cohort_definition_id = as.integer(str_sub(group_level, 8))) %>%
inner_join(cdm[["inc_pat"]] %>% select(cohort_definition_id, outcome_cohort_name) %>% distinct(), by = c("cohort_definition_id"), copy = TRUE ) %>%
select(-"cohort_definition_id") %>%
filter(variable_name %in% c("number subjects","number records","duration","number_exposures","cumulative_quantity",
"initial_quantity","initial_daily_dose_milligram","cumulative_dose_milligram"))

inc_use_summary <- bind_rows(inc_use_summary,use_drug_cohort)
}

**Comment by bmosseveld** [comment]
The new script is running.
Checking the data for this ingredient I found the following:

We have 595 exposures of drugs with this ingredient.
The durations of these exposures vary from 0 to 366 days.
There are 97 exposures of 0 days.

**Comment by tiozab** [comment]
@catalamarti duration of 0 days should be eliminated, no?

**Comment by tiozab** [comment]
@bmosseveld, thank you. Can you please run the rest of the code and upload the results in teams?

**Comment by bmosseveld** [comment]
It's running again.
The 0 days duration is actually 1 day.
In our source database the end date is the day after the last day the drug is used but in CDM the end date is the last day the drug is used. So, when the end date is equal to the start date (the ones I thought duration is 0 days in the comment above) have a duration of 1 day.
In CDM all end dates are inclusive.

**Comment by tiozab** [comment]
@bmosseveld, great, thanks, yes that is true, that is also how the study packages estimate duration (end-start+1) :-)
So we do not know why the code is happy with all drugs but imiglucerase

**Comment by bmosseveld** [comment]
Hi Theresa,

It did finish correctly now.
I have uploaded the results to Teams.

Kind regards,

Mees

***@***.***

Department of Medical Informatics
PO Box 2040, 3000 CA  Rotterdam,  The Netherlands
Visiting address: Room Na-2612, Dr. Molewaterplein 40, 3015 GD  Rotterdam
Tel.: +31 10 70 44183 (Monday - Thursday)
Fax.: +31 10 70 44722
E-mail: ***@***.******@***.***>
http://www.erasmusmc.nl/med_informatica/
http://www.ipci.nl<http://www.ipci.nl/>
