### ISSUE TITLE
CDMConnector error in creating denominator cohorts

### ISSUE THREAD

**Issue by tiozab** [oxford-pharmacoepi/MegaStudy#38]
@ablack3, we are having the following CDMConnector error in creating denominator cohorts @edward-burn in a redshift database by @rfherrerac

cdm <- generateDenominatorCohortSet(
  cdm = cdm, 
  name = "denominator",
  cohortDateRange = as.Date(c("2010-01-01",NA)),
  ageGroup = list(
    c(0, 150) 
  ),
  sex = c("Both"), 
  daysPriorObservation = c(0,30),   # 30 for incidence, 0 for prevalence
  requirementInteractions = TRUE
)

ℹ Creating denominator cohortsError in `CDMConnector::dateadd()`:! No known SQL translation

**Comment by tiozab** [comment]
@ablack3 and @edward-burn this exact code ran in CDMConnector 1.2.1 and IncPrev 0.6.0, however now in another code part we are using CDMConnector 1.3.0 and IncPrev 0.7.0 and we get this error.

**Comment by catalamarti** [comment]
@tiozab dbplyr 2.5.0 created this issue, if you are using this version of dbplyr you have to use the new version of the packages:
CDMConnector 1.3.1, IncidencePrevalence 0.7.2 and so on...Otherwise you can use dbplyr 2.4.0

**Comment by tiozab** [comment]
@catalamarti is it redshift specific? other db do not have this error

**Comment by tiozab** [comment]
@catalamarti forget what I said, yes 2.4.0 will be the correct version ;-)
