### ISSUE TITLE
GENERATE INCIDENT DRUG COHORTS: Error in eval(ei, envir) : std::bad_alloc

### ISSUE THREAD

**Issue by dandedman** [oxford-pharmacoepi/MegaStudy#43]
Hi @tiozab 

I am getting an error during the GENERATE INCIDENT DRUG COHORTS step. I tried it twice in case the first time was due to server patching in the background - both times it fails at the amoxicillin cohort. Log attached
[CPRDAurum2309_log.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/14994587/CPRDAurum2309_log.txt)

Console output:

> ...
> ...
> Created a temporary table named #dbplyr_057
> Created a temporary table named #dbplyr_059
> Created a temporary table named #dbplyr_061
> i Creating denominator cohorts
> v Cohorts created in 3 min and 51 sec
> Getting incidence for analysis 1 of 2
> Getting incidence for analysis 2 of 2
> Overall time taken: 28 mins and 3 secs
> ...
> ...
> Getting incidence for analysis 1 of 2
> Getting incidence for analysis 2 of 2
> Error in eval(ei, envir) : std::bad_alloc
> In addition: There were 16 warnings (use warnings() to see them)
> traceback()
> 20: stop(structure(list(message = "std::bad_alloc", call = eval(ei, 
>         envir), cppstack = NULL), class = c("std::bad_alloc", "C++Error", 
>     "error", "condition")))
> 19: result_insert_dataframe(rs@ptr, values, batch_rows)
> 18: tryCatchList(expr, classes, parentenv, handlers)
> 17: tryCatch(result_insert_dataframe(rs@ptr, values, batch_rows), 
>         finally = dbClearResult(rs))
> 16: .local(conn, name, value, ...)
> 15: DBI::dbWriteTable(conn = con, name = fullName, value = table) at 13-dbWriteTable.R#49
> 14: DBI::dbWriteTable(conn = con, name = fullName, value = table)
> 13: insertTable.db_cdm(cdm = getCdmSource(cdm), name = name, table = table, 
>         overwrite = overwrite)
> 12: insertTable(cdm = getCdmSource(cdm), name = name, table = table, 
>         overwrite = overwrite)
> 11: insertTable.cdm_reference(cdm = cdm, name = paste0(tablePrefix, 
>         "_p_", i), table = participants)
> 10: omopgenerics::insertTable(cdm = cdm, name = paste0(tablePrefix, 
>         "_p_", i), table = participants) at estimateIncidence.R#398
> 9: estimateIncidence(cdm = cdm, denominatorTable = "denominator", 
>        outcomeTable = "drug_cohorts", interval = "years", completeDatabaseIntervals = FALSE, 
>        outcomeWashout = 30, repeatedEvents = TRUE, minCellCount = 10, 
>        returnParticipants = TRUE) at DUS.R#177
> 8: eval(ei, envir)
> 7: eval(ei, envir)
> 6: withVisible(eval(ei, envir))
> 5: source(here("DUS.R")) at CodeToRun_Aurum2309.R#51
> 4: eval(ei, envir)
> 3: eval(ei, envir)
> 2: withVisible(eval(ei, envir))
> 1: source("C:/Users/dedmand.AUTH/Documents/R/MegaStudy/DUS Code/CodeToRun_Aurum2309.R", 
>        echo = TRUE)

**Comment by tiozab** [comment]
@dandedman lets remove amoxicillin 
please put the following into line 154 
concept_drugs <- within(concept_drugs, rm(amoxicillin))

and run again from line 154 (in case you still have your environment)

**Comment by carmenOT** [comment]
Hi @tiozab, I had a similar problem but it wouldn't execute the job for any of the drugs, I've tried as suggested to remove them. I guess I have a general error for which it doesn't pass this step I got no error apart from 

> ℹ Creating denominator cohorts
> ✔ Cohorts created in 4 min and 19 sec
> Getting incidence for analysis 1 of 2
> Getting incidence for analysis 2 of 2
> Killed
> Job Failed. Exiting...

Any suggestions?

**Comment by tiozab** [comment]
@carmenOT @dandedman this error is most likely due to your big big databases @dandedman ran the code without problems in a subset of the data. That said @carmenOT can you execute this code in a random sample of your data?
@dandedman I am inclined to suggest you upload the results from the 50 practices (is it more or less a random sample) ? Because it would be a pity to lose information on the amoxicillin which is quite an important drug.
@dandedman just wondering whether you had executed the IncidencePrevalence code ? we could not find your upload, and this step comes before DUS.

**Comment by dandedman** [comment]
@tiozab: sorry I thought I uploaded the incidence prevalence results already but apparently not - done now. For the 50 practice sample ('more or less' random) I can share it with you as an investigator for the RDG approved study, but before it is shared more publicly I would need to understand the potential for small cell counts - are these automatically suppressed? I imagine the amoxicillin results should be fine so it might be OK just to publish those. The other thing to note is that this database only contains results to early 2022, whereas the full Aurum goes to around May/June 2023.

**Comment by dandedman** [comment]
@tiozab: completed successfully on full db. Results uploaded (and for 50 practice sample)
