### ISSUE TITLE
DUS warnings in R: `/.integer64`(100 * impute$count, impute$exposures)

### ISSUE THREAD

**Issue by Merkelbach** [oxford-pharmacoepi/MegaStudy#44]
Hi all, 

I successfully ran the DUS code, and at first glance, the results appear satisfactory. However, during execution, I encountered a few warnings. Before proceeding further, I'd like to gather your thoughts on whether these warnings might pose any issues.
 
![DUS_warnings](https://github.com/oxford-pharmacoepi/MegaStudy/assets/50047487/05f6cd53-2a26-4534-a64b-b54c4c83a82f)

 Thanks in advance!
Manon

**Comment by tiozab** [comment]
@Merkelbach this should not be a problem. did you have a change to look at your DUS results in the Shiny to see if the results make sense? That is always the best check if it had been a successful execution :-)

**Comment by Merkelbach** [comment]
@tiozab thanks for the response, I had a look in Shiny, those result looks good to me. In that case  I can hand in my results :).
