### ISSUE TITLE
Error in `if (...) NULL`: ! argument is of length zero

### ISSUE THREAD

**Issue by AlvaroMartinezERPSS** [oxford-pharmacoepi/MegaStudy#45]
Hi,

We are having issues with _omopgenerics_ and _DrugUtilisation_ when running DUS.R

![image](https://github.com/oxford-pharmacoepi/MegaStudy/assets/128473608/c0dcb8a7-abac-4c5d-88e6-1ec3c579afe8)

Thanks

**Comment by tiozab** [comment]
@AlvaroMartinezERPSS thanks can you send me the log file (in the "storage" folder) so I can see where exactly the error occurred. It seems it is in the GENERATE INCIDENT DRUG COHORT, but it would be useful to see whether the error occurred right away or only at a specific drug. Thanks!

**Comment by AlvaroMartinezERPSS** [comment]
[hulafe_bbdd_DUS_log.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/15039696/hulafe_bbdd_DUS_log.txt)

Hi @tiozab, I attached the log file. Thank you!

**Comment by tiozab** [comment]
thanks @AlvaroMartinezERPSS, I see that it stops at 36857573 "CERTOLIZUMAB" in DRUG USE INCIDENT PATIENTS. it is possible that your vocabulary does not have this ingredient and therefore fails. the same will likely happen for 36863408 - CYTARABINE 5'-PHOSPHATE.

thus, in the script DUS.R 
in line 367 please remove the code 
36857573,   

and in line 378 please remove the code 
36863408, 

and in line 425 please remove the word
"CERTOLIZUMAB", 

and in line 436 please remove the word 
"CYTARABINE 5'-PHOSPHATE",

hope that fixes it :-)

if you still have your R environment open you can re-run from line 329
