### ISSUE TITLE
DUS Code runs out of memory

### ISSUE THREAD

**Issue by rekkasa** [oxford-pharmacoepi/MegaStudy#47]
While running the DUS code on the Papageorgiou General Hospital data we keep running out of memory. We were wondering if there are any system requirements for running the study (we are currently allocating 20Gb of RAM). I attach the R output and the log for your reference. We hope this will be resolved by allocating more resources, but we wanted your input on that.

- [papageorgiou_log.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/15104875/papageorgiou_log.txt)
- [R_output.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/15104887/R_output.txt)

Thank you very much in advance

**Comment by tiozab** [comment]
@rekkasa let's save what you have in your environment until this moment (the DUS of incident patient has finished). 
please run the following:
## zip everything together ---
info(logger, "ZIP EVERYTHING")
zip(
  zipfile = here::here(paste0("Results_DUS_inc_pat", cdmName(cdm), ".zip")),
  files = list.files(outputFolder),
  root = outputFolder
)

then re-start your r session to have everything cleared. 
The files created in the characterisation can become very large. 

Then you can run everything again, but do not source the DUS.R (as can be seen at the end of the CodeToRun.R), but only run the following parts of the DUS.R:
line 1 - 154, 
line 331 - 448,
line 488 - end

**Comment by rekkasa** [comment]
@tiozab thank you very much for the help! We managed to successfully run the DUS code.

You can go ahead and close the issue
