### ISSUE TITLE
DUS step: individual_indications - getCandidateCodes

### ISSUE THREAD

**Issue by Katrin-MLK** [oxford-pharmacoepi/MegaStudy#48]
Hi team, we are now in DUS step and getting error "invalid identifier 'CONCEPT_NAME'" in getCandidateCodes.
Any recommendation what to check? Thanks!
'> ## Generate indication concepts ----
'> info(logger, "GENERATE INDICATION CONCEPTS")
'> neutropenia <- getCandidateCodes(
'+   cdm = cdm,
'+   keywords = c("neutropenia","neutropenic"),'
'+   domains = c("Condition"),
'+   includeDescendants = FALSE
'+ )
condition domain: Limiting to domains of interest
condition: Getting concepts to include
Error in `dplyr::collect()`:
! Failed to collect lazy table.
Caused by error:
! nanodbc/nanodbc.cpp:1526: 00000: SQL compilation error: error line 51 at position 7
invalid identifier 'CONCEPT_NAME'

**Comment by tiozab** [comment]
@Katrin-MLK CONCEPT_NAME in capital letters may be a problem. every column should be lower case letters
