### ISSUE TITLE
problem restore library in Incidence/prevalence code

### ISSUE THREAD

**Issue by prubiom** [oxford-pharmacoepi/MegaStudy#51]
Hello, everyone

I'm a little bit frustrated with this. Every time I try to restore library to installa dependencies in this step, I obtain this error

![image](https://github.com/oxford-pharmacoepi/MegaStudy/assets/162588455/49e73f4c-6a8d-4748-8d32-0be22a7d7426)

Does anyone know what can I do?

Thank u!

**Comment by tiozab** [comment]
@prubiom renv can be a real pain!!
you can always install a package yourself, and R will ask you whether you want to install that in the renv folder and you just say yes ;-) I am not familiar with the MASS, however, I just checked you should install this verison: 
remotes::install_version("MASS", version = "7.3-60")
hope this helps!
