### ISSUE TITLE
DUS script - DEMOGRAPHICS INCIDENT PATIENTS error "result_type" column does not exist (summariseCharacteristics)

### ISSUE THREAD

**Issue by inesreinecke** [oxford-pharmacoepi/MegaStudy#55]
I receive the following error during characterisation of demographics of incident patients.

Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `result_type` doesn't exist.
---
Backtrace:
     ▆
  1. ├─inc_demographics_interim %>% ...
  2. ├─PatientProfiles::summariseCharacteristics(...)
  3. │ └─... %>% dplyr::select(!"result_type")
  4. ├─dplyr::select(., !"result_type")
  5. ├─dplyr:::select.data.frame(., !"result_type")
  6. │ └─tidyselect::eval_select(expr(c(...)), data = .data, error_call = error_call)
  7. │   └─tidyselect:::eval_select_impl(...)
  8. │     ├─tidyselect:::with_subscript_errors(...)
  9. │     │ └─base::withCallingHandlers(...)
 10. │     └─tidyselect:::vars_select_eval(...)
 11. │       └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 12. │         └─tidyselect:::eval_c(expr, data_mask, context_mask)
 13. │           └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 14. │             └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 15. │               └─tidyselect:::eval_bang(expr, data_mask, context_mask)
 16. │                 └─tidyselect:::walk_data_tree(expr[[2]], data_mask, context_mask)
 17. │                   └─tidyselect:::as_indices_sel_impl(...)
 18. │                     └─tidyselect:::as_indices_impl(...)
 19. │                       └─tidyselect:::chr_as_locations(x, vars, call = call, arg = arg)
 20. │                         └─vctrs::vec_as_location(...)
 21. └─vctrs (local) `<fn>`()
 22.   └─vctrs:::stop_subscript_oob(...)
 23.     └─vctrs:::stop_subscript(...)
 24.       └─rlang::abort(...)

**Comment by tiozab** [comment]
@inesreinecke  can you give me the following please:
packageVersion("CDMConnector")
packageVersion("omopgenerics")
packageVersion("DrugUtilisation")
packageVersion("PatientProfiles")
