### ISSUE TITLE
Report discrepancies in result data

### ISSUE THREAD

**Issue by michaelsfr** [oxford-pharmacoepi/MegaStudy#56]
Dear all, when reviewing our results, we noticed inconsistencies for a specific drug that indicated a strong shortage in the data. After cross-checking the data with our colleagues from oncology, we realized that this happened because there was no documentation of drug administration for specific diseases during this period. Is there any way that we can provide a brief explanation of the data? For example, a text/excel file in the Teams space? Otherwise this could lead to false assumptions.

**Comment by michaelsfr** [comment]
@tiozab put a short explanation file in the results folder in the EHDEN workspace and a brief comment in the cheatsheet. will very likely attend the webinar. see you!

**Comment by tiozab** [comment]
thanks @michaelsfr I moved the explanation file to the webinar folder as well, most appropriate place :-)
