### ISSUE TITLE
Incidence Attrition results

### ISSUE THREAD

**Issue by Dorian-APHM** [oxford-pharmacoepi/MegaStudy#57]
Hello,

I went through the feasability steps for APHM.
Now we're trying to complete Incidence Prevalence steps, the code ran without problem but the results seems to be suspicious.

Below a screenshot from the shiny application :

![Incidence attrition APHM](https://github.com/oxford-pharmacoepi/MegaStudy/assets/170933707/6bdc3eea-8d21-4330-89ec-5b31b326c2cb)

The starting population is good, but I don't understand why the variable Missing year of birth includes all the starting population while this data seems to be present in our cdm.
The same goes for Missing Sex.

Does anyone have an explanation ? What did I do wrong ?

Best regards,

Dorian

**Comment by tiozab** [comment]
hi @Dorian-APHM the numbers are the number of people retained, not the number dropped. 
So, I think your population looks good.

**Comment by Dorian-APHM** [comment]
Hi @tiozab, thanks for the reply, that's what we were thinking.
However, I can't see the results in ‘study results’. For example for amoxicilin which is mapped, and in the base we have this :

![Screenshot_20240530_102428](https://github.com/oxford-pharmacoepi/MegaStudy/assets/170933707/9dae5f8d-bb99-4c20-8497-736357f15b7b)

There must be a variable, an indicator or something else that is not in the base and that makes it impossible to display the results, but we can't find out what it is. Or maybe some filters to modify.

I've uploaded our results in the new results section under this name: Results_CDM_APHM_Incidence_Prevalence if that helps, as we can't find the solution.

**Comment by tiozab** [comment]
@Dorian-APHM sorry about that 
This should fix it, please amend the databases.csv according to your own information (cdm_name as seen in the snapshot)
https://github.com/oxford-pharmacoepi/MegaStudy/issues/62

**Comment by tiozab** [comment]
@Dorian-APHM did it work?

**Comment by DorianGsst** [comment]
Yes it works.

Thanks for the solution and sorry for the delay in replying.

Best regards,

Dorian

**Comment by Dorian-APHM** [comment]
Yes it works !

Thanks for the reply and sorry for the delay in replying.

Best regards,

Dorian

**Comment by tiozab** [comment]
Great! thanks!
