### ISSUE TITLE
Understanding "drug_type_concept_id = 32839"

### ISSUE THREAD

**Issue by salvagarcia** [oxford-pharmacoepi/MegaStudy#58]
Hi,
this is a question about the meaning of the drug_type_concept_id = 32839. I'm guessing that this filter is trying to abtain those prescriptions that were not finally dispensed (and thus reported as an issue).
We did not include them in out  OMOP database but we know how to do it. The fact is that in our primary datasource we have only 1161 prescriptions' issue documnented as "Medication not available", and this is the temporal distribution by years:

![med_not_available](https://github.com/oxford-pharmacoepi/MegaStudy/assets/30435836/8ca4a0a4-b7c2-4831-937c-7abaad565cc8)

Is this assuption correct? Should we proceed by adding these "issues" to the OMOP database and then run the Incidence_Prevalence part?

**Comment by tiozab** [comment]
@salvagarcia either post this in the EHDEN Teams or OHDSI Forum for community help.
This seems like a database specific thing though that you have this information available. Not many will have it. 
The right thing to do would be do "substract" this information from the prescriptions (since the medication was not available for that person), however the question is whether it is worth the effort. 
I think since there are so few, you can probably disregards this information for now.

**Comment by tiozab** [comment]
@salvagarcia thanks for sending the results, please continue with the drugUtilisationStudy step (DUS), it is the idea the we are characterising the patients from the incidence prevalence step. 
Thus, if you want to change your database, then you will need to re run both steps. They belong together :-)

**Comment by tiozab** [comment]
@salvagarcia great to see you yesterday in the webinar. Did you try to run the DUS?

**Comment by salvagarcia** [comment]
Hi @tiozab, yes I attended the first part. For the second I guess it was more oriented to make interpretation of the data and thus suitable for data scientists and other skills rather than just IT technicians.
Yes, the DUS was being executed while the webinar was ongoing, and it finished late in the afternoon. I've uploaded the results to the sharepoint (https://ehden.sharepoint.com/:u:/r/sites/EHDENMEGA/Gedeelde%20documenten/General/DUS/uploads%20from%20datapartners/new%20results/Results_DUS_ATENEA_OMOP.zip?csf=1&web=1&e=8BZ6rp) but I did not register it in any excel or so. Should I do anything else? Are we late on that or can these results still be usefull?
Thank you for your help.

**Comment by tiozab** [comment]
@salvagarcia perfect thank you. We will look at the DUS results in our next webinar in September. Perfect!

**Comment by tiozab** [comment]
@salvagarcia no worries, we hope you enjoyed the first part of the webinar. There will be an email with further updates. However, if you can fill in the description of your database, that would be amazing. https://ehden.sharepoint.com/:w:/r/sites/EHDENMEGA/Gedeelde%20documenten/General/Short%20descriptions%20of%20each%20database.docx?d=w3b7774a809374c4c84b226395c6e1660&csf=1&web=1&e=Zgf8B3
