### ISSUE TITLE
addDrugUse returned error when running DUS code

### ISSUE THREAD

**Issue by yl3613** [oxford-pharmacoepi/MegaStudy#59]
https://github.com/oxford-pharmacoepi/MegaStudy/blob/d15cf1b355178b356be8c7eef442d42c597c8852/DUS%20Code/DUS.R#L458
Hi Team, I got this error when running the DUS code on our data source. This error was caused by the "addDrugUse" on L458 of DUS.R. Is this because the version of the package I'm using? I'm using DrugUtilisation 0.5.0 

Error: Failed to prepare query: ERROR:  syntax error at or near "DISTINCT"
LINE 106:             "LHS"."amount_numeric" IS NOT DISTINCT FROM "dbp...
                                                    ^
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by tiozab** [comment]
Thanks! can you send me your log.txt file from the folder called "storage"? which database managment system are you using?

**Comment by yl3613** [comment]
Sure, see attached. We are using Amazon Redshift. 
[PMTX+_log.txt](https://github.com/user-attachments/files/15539461/PMTX%2B_log.txt)

**Comment by carmenOT** [comment]
@tiozab, the error seems to come from the DrugUtilisation package. Would it be worth sharing the issue [here](https://github.com/darwin-eu/DrugUtilisation)?

**Comment by tiozab** [comment]
it is not quite clear what the error is. 
please try to re-run with the new version posted here

**Comment by tiozab** [comment]
@yl3613 did it work?

**Comment by yl3613** [comment]
The issue was because the `sql_expr_matches` method was not compatible with Redshift SQL. The exact fix for it is included in this PR: https://github.com/tidyverse/dbplyr/pull/1522

**Comment by yl3613** [comment]
The issue was because the `sql_expr_matches` method was not compatible with Redshift SQL. The exact fix for it is included in this PR: https://github.com/tidyverse/dbplyr/pull/1522
