### ISSUE TITLE
Shiny app do not find and show incidence/prevalence results

### ISSUE THREAD

**Issue by lilliniroberto** [oxford-pharmacoepi/MegaStudy#62]
Dear colleagues, after computing incidence and prevalence (correctly as it seems to me), the Shiny app is not able to show such results, even if attrition and datadabase details are correctly shown. Can you help me?

Here you can find the warnings reported by the R consolle and in attachment two examples of the shiny and the csv results.

Thank you in advance
Roberto Lillini
![Incidence example](https://github.com/oxford-pharmacoepi/MegaStudy/assets/133981799/17308509-9e38-485d-8b9c-12471df6e44e)
![Shiny](https://github.com/oxford-pharmacoepi/MegaStudy/assets/133981799/2a90d879-41bd-4991-a7df-6ce8f47deb09)

**Comment by tiozab** [comment]
@lilliniroberto sorry for the inconvenience
We have added a file called databases.csv for the webinar and were not aware that this broke local use of the shiny. 
I have now added in the readme how to overcome this 
https://github.com/oxford-pharmacoepi/MegaStudy/tree/main/IncidencePrevalence%20Shiny

just change the databases.csv file accordingly please:

cdm_name, data_type, country
INT, ..., ....

**Comment by lilliniroberto** [comment]
Thank you Theresa, I’m on holiday till to Monday the 17th.

I will test the solution when I’m back and update you about.

Thank you again and cheers
Roberto

Da: Theresa Burkard ***@***.***>
Inviato: venerdì 7 giugno 2024 15:51
A: oxford-pharmacoepi/MegaStudy ***@***.***>
Cc: Lillini Roberto ***@***.***>; Mention ***@***.***>
Oggetto: Re: [oxford-pharmacoepi/MegaStudy] Shiny app do not find and show incidence/prevalence results (Issue #62)


@lilliniroberto<https://github.com/lilliniroberto> sorry for the inconvenience
We have added a file called databases.csv for the webinar and were not aware that this broke local use of the shiny.
I have now added in the readme how to overcome this
https://github.com/oxford-pharmacoepi/MegaStudy/tree/main/IncidencePrevalence%20Shiny

just change the databases.csv file accordingly please:

cdm_name, data_type, country
INT, ..., ....

**Comment by lilliniroberto** [comment]
Dear Theresa, thank you for your suggestion. Today I have tested the solution and it works. In the next days our colleagues at the  hospital pharmacy will check the results along with their data and then I will upload our incidence.

Have a nice day
Roberto

Da: Theresa Burkard ***@***.***>
Inviato: venerdì 7 giugno 2024 15:51
A: oxford-pharmacoepi/MegaStudy ***@***.***>
Cc: Lillini Roberto ***@***.***>; Mention ***@***.***>
Oggetto: Re: [oxford-pharmacoepi/MegaStudy] Shiny app do not find and show incidence/prevalence results (Issue #62)


@lilliniroberto<https://github.com/lilliniroberto> sorry for the inconvenience
We have added a file called databases.csv for the webinar and were not aware that this broke local use of the shiny.
I have now added in the readme how to overcome this
https://github.com/oxford-pharmacoepi/MegaStudy/tree/main/IncidencePrevalence%20Shiny

just change the databases.csv file accordingly please:

cdm_name, data_type, country
INT, ..., ....
