### ISSUE TITLE
n_missing_quantity not found in .data

### ISSUE THREAD

**Issue by martinr55** [oxford-pharmacoepi/MegaStudy#64]
Using duckdb I get the following error. It occurs during the final check ("diagnosticsSummary").

Error in `dplyr::mutate()`:
ℹ In argument: `missing_quantity_exp_start_end_days_supply = glue::glue("\n {.data$n_missing_quantity},
  {.data$n_missing_drug_exposure_start_date}, {.data$n_missing_drug_exposure_end_date}, {.data$n_missing_days_supply}")`.
Caused by error:
! Failed to evaluate glue component {.data$n_missing_quantity}
Caused by error in `.data$n_missing_quantity`:
! Column `n_missing_quantity` not found in `.data`.

**Comment by tiozab** [comment]
@martinr55 have you activated and restored the renv? 
It seems like you have used a more recent version of DrugExposureDiagnostics.
