### ISSUE TITLE
problem with colnames SIDIAP

### ISSUE THREAD

**Issue by fbarenyidi** [oxford-pharmacoepi/MegaStudy#67]
After running the 177 line there's an issue with the colnames, there's no colname
"outcome_start_date” in the "inc" dataset: see the colnames.
![image003](https://github.com/oxford-pharmacoepi/MegaStudy/assets/174479167/363db443-4737-413b-aa6e-ef6ebf1da251)

**Comment by tiozab** [comment]
@fbarenyidi thanks, we have seen this error here https://github.com/oxford-pharmacoepi/MegaStudy/issues/66 and it was resolved using the new renv and code provided in issue #53 (comment from May 24)

**Comment by fbarenyidi** [comment]
Hey Theresa, after using the DUS1point_4 script and the new r environment when I try to run the app I get this error:
<img width="639" alt="image" src="https://github.com/oxford-pharmacoepi/MegaStudy/assets/174479167/fc3b3f46-0b0f-47fc-9081-4a1839770974">
Do you know what could be the error? Thanks

**Comment by tiozab** [comment]
@fbarenyidi thanks, I just re-ran the shiny with my own 1.4 results and it works. If you do not have the newest version from the shiny, please pull (and do not forget to update the database csv with your database in the shiny), if it still does not work, you will have to wait for my new code amendments. but it should work with the current version.

**Comment by fbarenyidi** [comment]
Dear @tiozab , I think it has to do with the following package:
<img width="639" alt="Captura de pantalla 2024-07-09 a les 10 17 04" src="https://github.com/oxford-pharmacoepi/MegaStudy/assets/174479167/1e78964f-a131-4208-b0d8-3c1165cba871">

and then when the Shiny is run gives this error:
<img width="639" alt="Captura de pantalla 2024-07-09 a les 10 28 00" src="https://github.com/oxford-pharmacoepi/MegaStudy/assets/174479167/bb970138-a65d-4c77-972b-13a3b400129d">

Thanks

**Comment by tiozab** [comment]
@fbarenyidi has the renv worked properly ? so the DUS has not run yet?
Can you give me the following package versions please:

packageVersion("dbplyr")
packageVersion("CirceR")
packageVersion("CDMConnector")
packageVersion("IncidencePrevalence")
packageVersion("CodelistGenerator")
packageVersion("DrugUtilisation")
packageVersion("PatientProfiles")
packageVersion("omopgenerics")
packageVersion("CohortCharacteristics")

**Comment by fbarenyidi** [comment]
> packageVersion("dbplyr")
[1] ‘2.5.0’
> packageVersion("CirceR")
[1] ‘1.3.3’
> packageVersion("CDMConnector")
[1] ‘1.4.0’
> packageVersion("IncidencePrevalence")
[1] ‘0.7.2’
> packageVersion("CodelistGenerator")
[1] ‘2.2.2’
> packageVersion("DrugUtilisation")
[1] ‘0.6.0’
> packageVersion("PatientProfiles")
[1] ‘1.0.0’
> packageVersion("omopgenerics")
[1] ‘0.2.1’
> packageVer

**Comment by tiozab** [comment]
thanks @fbarenyidi can you send me your log from the storage folder. you are using Postgresql right? have you run the DUS_1point4.R file, right?

**Comment by fbarenyidi** [comment]
Yes, i run the DUS1_pont4.R file and with Postgresql. Here you have, I'm running it again if in any case there was a problem with the environment. 
[SIDIAP_log.txt](https://github.com/user-attachments/files/16140837/SIDIAP_log.txt)

**Comment by tiozab** [comment]
Thanks, the first time it stopped at demographics incident patients. does this work? inc_demographics <- cdm[["inc_pat"]]  %>%
            addDemographics(
              indexDate = "cohort_start_date",
              age = TRUE,
              ageName = "age",
              ageGroup = list(
                c(0,18),
                c(19,64),
                c(65,150)
              ),
              sex = TRUE,
              sexName = "sex",
              priorObservation = FALSE,
              futureObservation = FALSE,
            )

**Comment by tiozab** [comment]
@fbarenyidi would you like to have a call this week or next week to go through the issues?

**Comment by fbarenyidi** [comment]
Hey Theresa, let me run the code again to see if we are able to solve the issue. 
Otherwise, would it work for you nect week? I 'll keep you informed. Thanks!

**Comment by tiozab** [comment]
sometime it helps to clear everything, re-start r and re-do the renv etc.

**Comment by tiozab** [comment]
thank I have replied. If you can let me know in advance what the problem is I may have a better picture for helping.

**Comment by fbarenyidi** [comment]
Now it seems that the problem resides on the memory, you know if there would be any chance to solve this issue?
![image](https://github.com/user-attachments/assets/39ef6f6d-9e64-4a22-a327-d4be2d9396f9)

**Comment by tiozab** [comment]
@fbarenyidi sorry for the late answer, I was on holiday. In case this problem cannot be resolved, please re-run the code on a random subset of your cdm 
https://darwin-eu.github.io/CDMConnector/reference/cdmSample.html
