### ISSUE TITLE
could not find function "getDrugMissings"

### ISSUE THREAD

**Issue by ascotchmer** [oxford-pharmacoepi/MegaStudy#7]
When running executeChecks() I get an error saying that the function getDrugMissings could not be found.  This is also true for summariseDrugExposureDuration.

These functions should be included with the library DrugExposureDiagnostics and are listed in the vignette but they are not there. I have manually installed older versions from source but they are also missing these functions.

**Comment by tiozab** [comment]
which Database management system are you using?

that is really bizarre, we are requesting version 1.0.0 of DrugExposureDiagnostics (as from the renv lock).
can you give me a reprex when running the vignette of the package using eunomia data for example?
please use the steps from the readme from the DrugExposureDiagnostics repo: https://github.com/darwin-eu/DrugExposureDiagnostics

**Comment by tiozab** [comment]
@ascotchmer I see that you uploaded results from Novartis? Did everything work in the end?

**Comment by tiozab** [comment]
@ascotchmer Can you also please upload the snapshot.csv and log.txt in EHDEN? Thank you! @martapineda needs them to process the feasibility assessment in a standardised fashion :D
