### ISSUE TITLE
problem with DUS step after correcting overlapping observation_periods

### ISSUE THREAD

**Issue by lorettakiss** [oxford-pharmacoepi/MegaStudy#71]
There were some overlapping obs period times that we have corrected and now we are faced with the following error:
Generating 1 cohort
✔ Generating cohort (1/1) - covid_19) [51.6s]
Error in `validateGeneratedCohortSet()`:
! There is overlap between entries in the cohort, 20857 overlaps detected first 5:
$ cohort_definition_id <int> 1, 1, 1, 1, 1
$ subject_id <int> 37253, 37253, 37307, 37323, 37323
$ cohort_start_date <date> 2016-11-23, 2018-01-30, 2013-06-25, 2012-05-10, 2012-06-21
$ cohort_end_date <date> 2017-02-01, 2018-03-13, 2021-03-22, 2012-05-26, 2012-06-26
$ next_cohort_start_date <date> 2017-01-31, 2018-03-12, 2021-03-21, 2012-05-25, 2012-06-25
Run `rlang::last_trace()` to see where the error occurred.

**Comment by tiozab** [comment]
@lorettakiss please use the code provided in #53 (comment May 24) that should take care of it :-)

**Comment by hejatibor** [comment]
Thank you, we run it, and got a new error message. I opened a new issue for that: #73 
This one can be cosed (?).
