### ISSUE TITLE
datediff() not working with Microsoft SQL server

### ISSUE THREAD

**Issue by huiqili007** [oxford-pharmacoepi/MegaStudy#76]
I am running IncidencePrevelance code against the Swedish data in Microsoft SQL server.
The error message reported that `CDMConnector::datediff()`: No known SQL translation.

Hope I can get help. Thank you!
Best
Huiqi Li

**Comment by tiozab** [comment]
@huiqili007 can you give us the console output, log from storage folder. 
can you also make sure the renv worked succesfully ? 
which version of CDMConnector are you using?
package.version("CDMConnector")

**Comment by huiqili007** [comment]
Hi,
Oh sorry I did not think from that angle. You are right the CDMConnector is of a different version (1.5.0) from required.
After fixing the issue, the code works perfectly.
I apologise again for the unnecessary trouble.

BTW, it is not possible to install old version of "httpuv" and had to install the latest version, but that does not seem to influence anything.
MVH
Huiqi Li
