### ISSUE TITLE
DUS create empty denominator table

### ISSUE THREAD

**Issue by huiqili007** [oxford-pharmacoepi/MegaStudy#78]
I encounter a problem with MEGAstudy DUS code, see log below.
I checked and the denominator table is empty. 

> # Run the study
> source(here("DUS.R"))
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 59 candidate concepts identified
Time taken: 0 minutes and 36 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 18 candidate concepts identified
Time taken: 0 minutes and 22 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 7659 candidate concepts identified
Time taken: 2 minutes and 56 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 265 candidate concepts identified
Time taken: 2 minutes and 34 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 41 candidate concepts identified
Time taken: 0 minutes and 26 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
procedure domain: Adding descendants
✔ 1451 candidate concepts identified
Time taken: 5 minutes and 16 seconds
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
✔ 1127 candidate concepts identified
Time taken: 0 minutes and 37 seconds
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
✔ 113 candidate concepts identified
Time taken: 0 minutes and 28 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 19 candidate concepts identified
Time taken: 2 minutes and 50 seconds
observation domain: Limiting to domains of interest
observation: Getting concepts to include
observation domain: Adding descendants
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
procedure domain: Adding descendants
✔ 77 candidate concepts identified
Time taken: 5 minutes and 24 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 208 candidate concepts identified
Time taken: 2 minutes and 54 seconds
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
procedure domain: Adding descendants
✔ 166 candidate concepts identified
Time taken: 2 minutes and 51 seconds
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
procedure domain: Adding descendants
✔ 1066 candidate concepts identified
Time taken: 2 minutes and 45 seconds
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
procedure domain: Adding descendants
✔ 578 candidate concepts identified
Time taken: 3 minutes and 4 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 107 candidate concepts identified
Time taken: 3 minutes and 4 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 145 candidate concepts identified
Time taken: 2 minutes and 52 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 21 candidate concepts identified
Time taken: 0 minutes and 24 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 333 candidate concepts identified
Time taken: 3 minutes and 14 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 9 candidate concepts identified
Time taken: 0 minutes and 29 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 123 candidate concepts identified
Time taken: 0 minutes and 27 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 103 candidate concepts identified
Time taken: 3 minutes and 1 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 194 candidate concepts identified
Time taken: 2 minutes and 43 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 220 candidate concepts identified
Time taken: 2 minutes and 59 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 47 candidate concepts identified
Time taken: 0 minutes and 28 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 337 candidate concepts identified
Time taken: 2 minutes and 36 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 50 candidate concepts identified
Time taken: 2 minutes and 33 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 83 candidate concepts identified
Time taken: 2 minutes and 44 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 76 candidate concepts identified
Time taken: 2 minutes and 35 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 17 candidate concepts identified
Time taken: 2 minutes and 35 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 27 candidate concepts identified
Time taken: 2 minutes and 40 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 78 candidate concepts identified
Time taken: 0 minutes and 26 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 11 candidate concepts identified
Time taken: 0 minutes and 25 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 61 candidate concepts identified
Time taken: 3 minutes and 2 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 58 candidate concepts identified
Time taken: 0 minutes and 27 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 5 candidate concepts identified
Time taken: 0 minutes and 27 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 19 candidate concepts identified
Time taken: 0 minutes and 24 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 27 candidate concepts identified
Time taken: 2 minutes and 54 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 3 candidate concepts identified
Time taken: 0 minutes and 28 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 8 candidate concepts identified
Time taken: 0 minutes and 23 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
observation domain: Limiting to domains of interest
observation: Getting concepts to include
observation domain: Adding descendants
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
procedure domain: Adding descendants
✔ 61 candidate concepts identified
Time taken: 7 minutes and 53 seconds
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
✔ 3072 candidate concepts identified
Time taken: 0 minutes and 40 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
observation domain: Limiting to domains of interest
observation: Getting concepts to include
observation domain: Adding descendants
✔ 16 candidate concepts identified
Time taken: 5 minutes and 16 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 5 candidate concepts identified
Time taken: 3 minutes and 0 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
measurement domain: Limiting to domains of interest
measurement: Getting concepts to include
observation domain: Limiting to domains of interest
observation: Getting concepts to include
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
✔ 68 candidate concepts identified
Time taken: 0 minutes and 33 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 134 candidate concepts identified
Time taken: 0 minutes and 26 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 4 candidate concepts identified
Time taken: 0 minutes and 23 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 40 candidate concepts identified
Time taken: 2 minutes and 35 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 22 candidate concepts identified
Time taken: 2 minutes and 43 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 12 candidate concepts identified
Time taken: 2 minutes and 54 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 5 candidate concepts identified
Time taken: 0 minutes and 34 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
procedure domain: Limiting to domains of interest
procedure: Getting concepts to include
✔ 5 candidate concepts identified
Time taken: 0 minutes and 45 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 20 candidate concepts identified
Time taken: 0 minutes and 27 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
✔ 23 candidate concepts identified
Time taken: 0 minutes and 30 seconds
condition domain: Limiting to domains of interest
condition: Getting concepts to include
condition domain: Adding descendants
✔ 113 candidate concepts identified
Time taken: 2 minutes and 50 seconds
ℹ Generating 1 cohort
✔ Generating cohort (1/1) - covid_19) [16m 21.6s]
Created a temporary table named #dbplyr_065
Created a temporary table named #dbplyr_066
Created a temporary table named #dbplyr_067
Created a temporary table named #dbplyr_068
Created a temporary table named #dbplyr_069
Created a temporary table named #dbplyr_070
Created a temporary table named #dbplyr_071
Created a temporary table named #dbplyr_072
Created a temporary table named #dbplyr_073
Created a temporary table named #dbplyr_074
Created a temporary table named #dbplyr_075
Created a temporary table named #dbplyr_076
Created a temporary table named #dbplyr_077
Created a temporary table named #dbplyr_078
Created a temporary table named #dbplyr_079
Created a temporary table named #dbplyr_080
Created a temporary table named #dbplyr_081
Created a temporary table named #dbplyr_082
Created a temporary table named #dbplyr_083
Created a temporary table named #dbplyr_084
Created a temporary table named #dbplyr_085
Created a temporary table named #dbplyr_086
Created a temporary table named #dbplyr_087
Created a temporary table named #dbplyr_088
Created a temporary table named #dbplyr_089
Created a temporary table named #dbplyr_090
Created a temporary table named #dbplyr_091
Created a temporary table named #dbplyr_092
Created a temporary table named #dbplyr_093
Created a temporary table named #dbplyr_094
Created a temporary table named #dbplyr_095
Created a temporary table named #dbplyr_096
Created a temporary table named #dbplyr_097
Created a temporary table named #dbplyr_098
Created a temporary table named #dbplyr_099
Created a temporary table named #dbplyr_100
Created a temporary table named #dbplyr_101
Created a temporary table named #dbplyr_102
Created a temporary table named #dbplyr_103
Created a temporary table named #dbplyr_104
Created a temporary table named #dbplyr_105
Created a temporary table named #dbplyr_106
Created a temporary table named #dbplyr_107
Created a temporary table named #dbplyr_108
Created a temporary table named #dbplyr_109
Created a temporary table named #dbplyr_110
Created a temporary table named #dbplyr_111
Created a temporary table named #dbplyr_112
Created a temporary table named #dbplyr_113
Created a temporary table named #dbplyr_114
Created a temporary table named #dbplyr_115
Created a temporary table named #dbplyr_116
Created a temporary table named #dbplyr_118
Created a temporary table named #dbplyr_120
Created a temporary table named #dbplyr_122
Created a temporary table named #dbplyr_124
Created a temporary table named #dbplyr_126
ℹ Creating denominator cohorts
✔ Cohorts created in 0 min and 20 sec
Error in `dplyr::collect()` at omopgenerics/R/classCdmTable.R:51:3:
! Failed to collect lazy table.
Caused by error:
! nanodbc/nanodbc.cpp:1769: 42000: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near ')'.  [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Statement(s) could not be prepared. 
<SQL> 'SELECT COUNT(*) AS "n"
FROM (
  SELECT "q01".*
  FROM (
    SELECT
      TRY_CAST(TRY_CAST("cohort_definition_id" AS NUMERIC) AS INT) AS "cohort_definition_id",
      TRY_CAST(TRY_CAST("subject_id" AS NUMERIC) AS INT) AS "subject_id",
      TRY_CAST("cohort_start_date" AS DATE) AS "cohort_start_date",
      TRY_CAST("cohort_end_date" AS DATE) AS "cohort_end_date"
    FROM "intrm"."scifi-pearl_denominator"
  ) "q01"
  WHERE (0)
) "q01"'
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
- No people found for denominator population

**Comment by tiozab** [comment]
@huiqili007 thanks that is the console output, can you send me the log from the storage folder as well please so I can see where the error occurred exactly. thanks :-)

**Comment by huiqili007** [comment]
Sure! Here it is
[scifi-pearl_log.txt](https://github.com/user-attachments/files/16712252/scifi-pearl_log.txt)

**Comment by tiozab** [comment]
can you run this 

cdm$denominator

**Comment by huiqili007** [comment]
> cdm$denominator
# Source:   SQL [0 x 4]
# Database: Microsoft SQL Server 16.00.1110[huiqi@scifi02-p/scifi_pearl]
# ℹ 4 variables: cohort_definition_id <int>, subject_id <int>, cohort_start_date <date>,
#   cohort_end_date <date>

**Comment by huiqili007** [comment]
![image](https://github.com/user-attachments/assets/5662dfe3-4a61-46dc-84e2-e4124f85d74b)

**Comment by tiozab** [comment]
it is indeed empty, so s.th. did not work. however, it is the same command (just fewer strata) as in the IncPrev code

**Comment by tiozab** [comment]
did the renv work correctly? that is the only thing I can think of right now

**Comment by tiozab** [comment]
@edward-burn any ideas how the denominator can be empty in megastudy DUS code but not in the megastudy IncPrev code?

**Comment by tiozab** [comment]
not important packages, just follow the instructions in ?renv::status()

@huiqili007 what does this return? 

cdm <- generateDenominatorCohortSet(
  cdm = cdm, 
  name = "denominator",
  cohortDateRange = as.Date(c("2010-01-01",NA)),
  ageGroup = list(
    c(0, 150) 
  ),
  sex = c("Both"), 
  daysPriorObservation = c(0,30),   
  requirementInteractions = TRUE
)

**Comment by huiqili007** [comment]
I see... gender concept in Person table is wrong in our data. Sorry for the trouble.
