### ISSUE TITLE
birth_datetime column not found

### ISSUE THREAD

**Issue by Katrin-MLK** [oxford-pharmacoepi/MegaStudy#8]
Hi all, 
we are using CDM in a Snowflake data warehouse. When we run the feasibility code, we get the error message "Error in assert_tables (): birth_datetime column not found in person table".
We investigated and it comes when using CDMConnector cdm function. It is assuming all column names are lower case, but in our environment column names are uppercase, so it does not find it. Does anyone had the same and has found a workaround?
Thanks.

**Comment by yichienlee2** [comment]
Hi @Katrin-MLK , I am encountering the same issue and we are discussing under #6 .

**Comment by Katrin-MLK** [comment]
Hi @yichienlee2, this is to report back that we are no longer facing the issue with the columns not found, although we have not changed anything. We were able to run the feasibility code on our databases successfully now, although having uppercase column names. It seems that the version of CDMConnector we are now using 0.5.1. maybe now handles the upper/lower case columns issue.
